openapi: 3.0.1
info:
  title: backend
  version: '1.0'
paths:
  /api/OidcConfiguration:
    get:
      tags:
        - Oidc
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/OidcConfiguration'
            application/json:
              schema:
                $ref: '#/components/schemas/OidcConfiguration'
            text/json:
              schema:
                $ref: '#/components/schemas/OidcConfiguration'
components:
  schemas:
    OidcConfiguration:
      type: object
      properties:
        authority:
          type: string
          nullable: true
        clientId:
          type: string
          nullable: true
        redirectUrl:
          type: string
          nullable: true
        postLogoutRedirectUrl:
          type: string
          nullable: true
        silentRedirectUrl:
          type: string
          nullable: true
        scopes:
          type: string
          nullable: true
      additionalProperties: false